const materials = [
  {name:'PS 1mm',category:'rigidos',label:'Rígido · Poliestireno',accent:'#00d8e8',print:'UV direto · 4x0',size:'100 × 200 cm',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, CDR',desc:'Chapa leve e versátil para sinalização interna, displays, testeiras e comunicação de ponto de venda. Excelente definição de impressão e corte preciso.',image:'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=1100&q=85',rate:0.095},
  {name:'PS 2mm',category:'rigidos',label:'Rígido · Poliestireno',accent:'#00d8e8',print:'UV direto · 4x0 / 4x4',size:'100 × 200 cm',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, CDR',desc:'Mais estrutura para placas, displays e peças promocionais. Superfície uniforme, ótima aderência de tinta e acabamento profissional.',image:'https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?auto=format&fit=crop&w=1100&q=85',rate:0.12},
  {name:'PVC 3mm',category:'rigidos',label:'Rígido · PVC Expandido',accent:'#f00073',print:'UV direto · alta definição',size:'122 × 244 cm',deadline:'3 a 5 dias úteis',files:'PDF, AI, EPS, CDR',desc:'Material resistente e leve para sinalização, cenografia e PDV. Aceita corte especial e mantém ótimo desempenho em ambientes internos.',image:'https://images.unsplash.com/photo-1557682250-33bd709cbe85?auto=format&fit=crop&w=1100&q=85',rate:0.17},
  {name:'PVC 5mm',category:'rigidos',label:'Rígido · PVC Expandido',accent:'#f00073',print:'UV direto · alta definição',size:'122 × 244 cm',deadline:'3 a 5 dias úteis',files:'PDF, AI, EPS, CDR',desc:'Chapa robusta para projetos que exigem maior estabilidade. Indicada para painéis, letras, sinalização e estruturas promocionais.',image:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1100&q=85',rate:0.23},
  {name:'Polionda',category:'rigidos',label:'Rígido · Polipropileno',accent:'#ffd600',print:'UV direto · 4x0',size:'130 × 200 cm',deadline:'2 a 3 dias úteis',files:'PDF, AI, CDR',desc:'Leve, econômico e resistente à umidade. Uma solução eficiente para placas temporárias, campanhas e sinalização imobiliária.',image:'https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=1100&q=85',rate:0.08},
  {name:'Capacho',category:'rigidos',label:'Rígido · Vinil',accent:'#ffd600',print:'UV · recorte personalizado',size:'120 × 600 cm',deadline:'5 a 7 dias úteis',files:'PDF, AI, CDR',desc:'Capacho vinílico personalizado para entradas comerciais. Impressão resistente, superfície lavável e recorte sob medida.',image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1100&q=85',rate:0.29},
  {name:'Acrílico',category:'rigidos',label:'Rígido · Acrílico',accent:'#00d8e8',print:'UV · branco localizado',size:'200 × 300 cm',deadline:'5 a 8 dias úteis',files:'PDF, AI, EPS',desc:'Acabamento premium com brilho, transparência e precisão. Ideal para placas, displays, letras e projetos de sinalização sofisticados.',image:'https://images.unsplash.com/photo-1557682224-5b8590cd9ec5?auto=format&fit=crop&w=1100&q=85',rate:0.38},
  {name:'Adesivo Brilho ou Fosco',category:'flexiveis',label:'Flexível · Vinil',accent:'#00d8e8',print:'Eco solvente · alta definição',size:'103, 124 ou 150 cm × contínuo',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, TIFF',desc:'Vinil autoadesivo disponível com acabamento brilhante ou fosco. A largura de 150 cm está sujeita à consulta de estoque.',image:'imagens%20flexiveis/adesivo%20brilho%20ou%20fosco.png',rate:35},
  {name:'Adesivo Transparente',category:'flexiveis',label:'Flexível · Vinil',accent:'#f00073',print:'Eco solvente · alta definição',size:'103 ou 124 cm × contínuo',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, TIFF',desc:'Filme transparente para aplicação em vidros, acrílicos e outras superfícies que pedem passagem de luz.',image:'imagens%20flexiveis/adesivo%20transparente.png',rate:35},
  {name:'Adesivo Jateado',category:'flexiveis',label:'Flexível · Vinil',accent:'#ffd600',print:'Eco solvente · alta definição',size:'98 ou 118 cm × contínuo',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, TIFF',desc:'Adesivo com efeito jateado para privacidade e decoração de vidros, divisórias e vitrines.',image:'imagens%20flexiveis/adesivo%20jateado.png',rate:35},
  {name:'Adesivo Perfurado',category:'flexiveis',label:'Flexível · Vinil',accent:'#00d8e8',print:'Eco solvente · alta definição',size:'134 cm × contínuo',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, TIFF',desc:'Vinil perfurado indicado para comunicação visual em vidros, mantendo visibilidade pelo lado interno.',image:'imagens%20flexiveis/adesivo%20perfurado.png',rate:48},
  {name:'Adesivo Automotivo',category:'flexiveis',label:'Flexível · Vinil',accent:'#f00073',print:'Eco solvente · alta definição',size:'134 cm × contínuo (consultar estoque)',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, TIFF',desc:'Vinil indicado para personalização e comunicação visual automotiva. Disponibilidade sujeita à consulta de estoque.',image:'imagens%20flexiveis/adesivo%20automotivo.png',rate:60},
  {name:'Adesivo Blackout Brilho ou Fosco',category:'flexiveis',label:'Flexível · Vinil',accent:'#ffd600',print:'Eco solvente · alta definição',size:'103, 124 ou 150 cm × contínuo',deadline:'2 a 4 dias úteis',files:'PDF/X-1a, AI, TIFF',desc:'Vinil opaco com acabamento brilhante ou fosco, ideal para bloquear a visualização da superfície. A largura de 150 cm está sujeita à consulta de estoque.',image:'imagens%20flexiveis/adesivo%20blackout%20e%20fosco.png',rate:35}
];

materials.forEach((material) => {
  material.deadline = '1 a 4 dias úteis';
  material.files = 'PDF, AI, PSD, CDR, EPS, TIFF, PNG e JPG';
});

const grid=document.querySelector('#materialGrid'), search=document.querySelector('#searchInput'), count=document.querySelector('#resultCount'), empty=document.querySelector('#emptyState');
let activeFilter='todos', currentMaterial=null;
function render(){
  const term=search.value.toLocaleLowerCase('pt-BR').trim();
  const filtered=materials.filter(m=>(activeFilter==='todos'||m.category===activeFilter)&&`${m.name} ${m.label} ${m.print} ${m.desc}`.toLocaleLowerCase('pt-BR').includes(term));
  grid.innerHTML=filtered.map((m)=>{const original=materials.indexOf(m);return `<button class="material-card" style="--accent:${m.accent};animation-delay:${Math.min(original*.035,.25)}s" data-id="${original}" aria-label="Ver detalhes de ${m.name}"><div class="card-image"><img src="${m.image}" alt="Aplicação visual de ${m.name}" loading="lazy"><span class="card-index">${String(original+1).padStart(2,'0')}</span><span class="card-arrow">↗</span></div><div class="card-info"><small>${m.label.toUpperCase()}</small><h3>${m.name}</h3><div class="card-meta"><span>${m.size}</span><span>${m.deadline}</span></div></div></button>`}).join('');
  count.textContent=`${filtered.length} ${filtered.length===1?'material disponível':'materiais disponíveis'}`; empty.hidden=filtered.length>0; grid.hidden=filtered.length===0;
}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));
search.addEventListener('input',render); document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus()}if(e.key==='Escape')closeModal()});
grid.addEventListener('click',e=>{const card=e.target.closest('.material-card');if(card)openModal(+card.dataset.id)});
const modal=document.querySelector('#detailModal');
function openModal(id){const m=materials[id];currentMaterial=m;document.querySelector('#detailImage').src=m.image;document.querySelector('#detailImage').alt=`Aplicação de ${m.name}`;document.querySelector('#detailIndex').textContent=`${String(id+1).padStart(2,'0')} / ${materials.length}`;document.querySelector('#detailCategory').textContent=m.label;document.querySelector('#detailTitle').textContent=m.name;document.querySelector('#detailDescription').textContent=m.desc;document.querySelector('#specPrint').textContent=m.print;document.querySelector('#specSize').textContent=m.size;document.querySelector('#specDeadline').textContent=m.deadline;document.querySelector('#specFiles').textContent=m.files;document.querySelector('.detail-label small').style.color=m.accent;document.querySelector('.quote-form').style.borderColor=m.accent;document.querySelector('#quotePrice').value='Sob consulta';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>document.querySelector('.close-btn').focus(),300)}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));
['quoteQty','quoteWidth','quoteHeight'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',calculatePrice));
function calculatePrice(){const q=+document.querySelector('#quoteQty').value,w=+document.querySelector('#quoteWidth').value,h=+document.querySelector('#quoteHeight').value;if(currentMaterial&&q&&w&&h){const minimum=25,calculated=currentMaterial.category==='flexiveis'?(w*h*q*currentMaterial.rate)/10000:(w*h*q*currentMaterial.rate)/100,total=Math.max(minimum,calculated);document.querySelector('#quotePrice').value=total.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}else document.querySelector('#quotePrice').value='Sob consulta'}
document.querySelector('#quoteForm').addEventListener('submit',e=>{e.preventDefault();closeModal();const toast=document.querySelector('#toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4000)});
document.querySelector('#headerQuote').addEventListener('click',()=>{document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'});search.focus()});
render();
